name: Build and Package FERAL HTPC

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      # BUMPED to v6
      uses: actions/checkout@v6

    - name: Setup .NET 10
      # BUMPED to v5
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'

    - name: Publish .NET Application
      run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true

    - name: Compile Inno Setup Installer
      run: |
        & "C:\Program Files (x86)\Inno Setup 6\iscc.exe" FeralInstaller.iss

    - name: Upload Installer Artifact
      # BUMPED to v7
      uses: actions/upload-artifact@v7
      with:
        name: Feral-HTPC-Installer
        path: Output/Feral_HTPC_Alpha_Setup.exe
